#!/usr/bin/env bash
#
# Configure rootless podman storage for the filesystem it actually sits on.
#
# Why this is a script and not a static config file: the correct graph driver
# depends on the filesystem backing ~/.local/share/containers, which nix cannot
# know at build time. The Arch laptop is btrfs, where the default overlay driver
# refuses to work:
#
#   'overlay' is not supported over btrfs ... backing file system is unsupported
#
# WSL is usually ext4, where overlay is correct and forcing btrfs would break it
# the same way. So detect, then write only what is needed.
#
# Also handles the part a config file cannot: a store already initialized with
# the wrong driver keeps being used (and keeps failing) until it is removed.
#
# Idempotent. Safe to run from bootstrap.sh and from home-manager activation.
#
#   --dry-run   print what would change, touch nothing
#   --quiet     only print on change or error
set -euo pipefail

MARKER='# managed by .mico (scripts/podman-storage.sh) - edits are overwritten'

dry_run=0
quiet=0

for arg in "$@"; do
  case "$arg" in
  --dry-run) dry_run=1 ;;
  --quiet) quiet=1 ;;
  *)
    printf 'podman-storage: unknown argument %s\n' "$arg" >&2
    exit 2
    ;;
  esac
done

# Overridable for testing.
storage_root="${PODMAN_STORAGE_ROOT:-$HOME/.local/share/containers/storage}"
storage_conf="${PODMAN_STORAGE_CONF:-$HOME/.config/containers/storage.conf}"

say() {
  ((quiet)) || printf 'podman-storage: %s\n' "$1"
}

changed() {
  printf 'podman-storage: %s\n' "$1"
}

warn() {
  printf 'podman-storage: warning: %s\n' "$1" >&2
}

act() {
  if ((dry_run)); then
    printf 'podman-storage: would run: %s\n' "$*"
    return 0
  fi
  "$@"
}

if ! command -v podman >/dev/null; then
  say "podman not installed, nothing to do"
  exit 0
fi

# Filesystem of the deepest existing ancestor - the storage dir itself may not
# exist yet on a fresh machine.
fs_type() {
  local path="$1"
  while [[ ! -e $path && $path != / ]]; do
    path="$(dirname "$path")"
  done
  if command -v findmnt >/dev/null; then
    findmnt --noheadings --output FSTYPE --target "$path" 2>/dev/null && return 0
  fi
  # Busybox-free fallback; prints e.g. "btrfs" or "ext2/ext3".
  stat -f -c %T "$path" 2>/dev/null || true
}

fs="$(fs_type "$storage_root")"
if [[ -z $fs ]]; then
  warn "could not determine filesystem for $storage_root, leaving storage alone"
  exit 0
fi

# Only btrfs needs an override. Everywhere else podman's default (overlay) is
# right, so we deliberately write no config at all.
case "$fs" in
btrfs) want="btrfs" ;;
*) want="overlay" ;;
esac

say "$storage_root is on $fs, driver should be $want"

# ---------------------------------------------------------------------------
# storage.conf
# ---------------------------------------------------------------------------
conf_is_ours() {
  [[ -f $storage_conf ]] && grep -qF "$MARKER" "$storage_conf"
}

if [[ -f $storage_conf ]] && ! conf_is_ours; then
  # A hand-written or distro-provided config outranks us.
  warn "$storage_conf exists and is not managed here, not touching it"
elif [[ $want == "btrfs" ]]; then
  if conf_is_ours && grep -q 'driver = "btrfs"' "$storage_conf"; then
    say "storage.conf already selects the btrfs driver"
  else
    changed "writing $storage_conf (driver = btrfs)"
    act mkdir -p "$(dirname "$storage_conf")"
    if ((dry_run)); then
      printf 'podman-storage: would write driver = "btrfs"\n'
    else
      cat >"$storage_conf" <<EOF
$MARKER
#
# Home is on btrfs; the default overlay driver cannot back onto it.
# Regenerated by scripts/podman-storage.sh (bootstrap.sh / home-manager).
[storage]
driver = "btrfs"
EOF
    fi
  fi
elif conf_is_ours; then
  # Filesystem changed under us (restore onto ext4, new machine, ...).
  changed "removing $storage_conf, $fs does not need a driver override"
  act rm -f "$storage_conf"
fi

# ---------------------------------------------------------------------------
# Existing store
#
# podman names its graph dirs after the driver (overlay-layers, btrfs-layers).
# A store built with the wrong one is not migrated, it just keeps erroring, so
# it has to go.
# ---------------------------------------------------------------------------
existing_driver() {
  local dir base
  for dir in "$storage_root"/*-layers; do
    [[ -e $dir ]] || continue
    base="$(basename "$dir")"
    printf '%s\n' "${base%-layers}"
    return 0
  done
  return 1
}

if existing="$(existing_driver)"; then
  if [[ $existing == "$want" ]]; then
    say "existing store already uses the $existing driver"
  else
    # Guard the rm: only ever inside the containers storage dir.
    case "$storage_root" in
    */containers/storage) ;;
    *)
      warn "refusing to remove unexpected storage path $storage_root"
      exit 1
      ;;
    esac

    changed "removing $existing store at $storage_root (incompatible with $want)"
    changed "local images and containers are dropped - they are rebuildable"

    if command -v systemctl >/dev/null && [[ -d /run/systemd/system ]]; then
      act systemctl --user stop podman.socket podman.service 2>/dev/null || true
    fi

    act rm -rf "$storage_root"

    if command -v systemctl >/dev/null && [[ -d /run/systemd/system ]]; then
      if systemctl --user is-enabled podman.socket &>/dev/null; then
        act systemctl --user start podman.socket 2>/dev/null || true
      fi
    fi
  fi
else
  say "no store initialized yet, podman will create a $want one"
fi

# ---------------------------------------------------------------------------
# Verify, so a silent misconfiguration cannot survive a bootstrap run.
# ---------------------------------------------------------------------------
if ((dry_run)); then
  exit 0
fi

got="$(podman info --format '{{.Store.GraphDriverName}}' 2>/dev/null || true)"
if [[ -z $got ]]; then
  warn "podman info failed - run 'podman info' to see the error"
  exit 0
fi

if [[ $got == "$want" ]]; then
  say "podman reports the $got driver"
else
  warn "podman reports '$got' but '$want' was expected"
  warn "inspect $storage_conf and $storage_root"
fi
