-- Shared nerd-font glyphs. Pure data — safe to require from plugins and keymaps.
return {
	ActiveLSP = "",
	DapBreakpoint = "",
	DapBreakpointCondition = "",
	DapBreakpointRejected = "",
	DapLogPoint = ".>",
	DapStopped = "󰁕",
	Database = "",
	Debugger = "",
	DefaultFile = "󰈙",
	Diagnostic = "󰒡",
	DiagnosticError = "",
	DiagnosticHint = "󰌵",
	DiagnosticInfo = "󰋼",
	DiagnosticWarn = "",
	FileModified = "",
	Git = "󰊢",
	GitBranch = "",
	LSPLoading = "󰒓",
	MacroRecording = "",
	Notes = "󰅌",
	Package = "󰏖",
	Rest = "󰖟",
	Search = "",
	Test = "󰙨",
	UI = "󰙵",
	Window = "",
}
